### ISSUE TITLE
Add "how-to-build" info to README.md

### ISSUE THREAD

**Issue by filfreire** [rafaelcpalmeida/Countdowner#1]
Add "how-to-build" information to the `README.md` file so anyone can easily clone/fork the repository and know how to build locally.

/cc @rafaelcpalmeida

**Comment by rafaelcpalmeida** [comment]
Great suggestion! I'll edit the `README.md` and append that information.

Thanks for the tip!

**Comment by rafaelcpalmeida** [comment]
Done ✌️
